name: Wokwi CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: wokwi/wokwi-ci-action@v1
        with:
          token: ${{ secrets.WOKWI_CI_TOKEN }}